version: "3.8"

services:
  app:
    build: .
    command: python src/main.py
    env_file:
      - ./env/app.env
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - reviews_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/db.env

volumes:
  reviews_postgres_data:
